server:
  port: 9092

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9191/uaa/user

spring:
  boot:
    admin:
      url: http://localhost:9999
  data:
    mongodb:
      database: neatlicity
    rest:
      basePath: /data
  jackson:
    serialization:
      writeDatesAsTimestamps: false
