server:
  port: 9092

spring:
  boot:
    admin:
      url: http://localhost:9999
  data:
    mongodb:
      database: neatlicity
    rest:
      basePath: /data
  jackson:
    serialization:
      writeDatesAsTimestamps: false