spring:
  boot:
    admin:
      url: http://localhost:9999

zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: api-user
    api-todo:
      path: /api/todo/**
      serviceId: api-todo
    api-reminder:
      path: /api/reminder/**
      serviceId: api-reminder
    api-quote:
      path: /api/quote/**
      serviceId: api-quote
    api-weather:
      path: /api/weather/**
      serviceId: api-weather
