spring:
  boot:
    admin:
      url: http://localhost:9999

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9191/uaa/user

zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: api-user
    api-device:
      path: /api/device/**
      serviceId: api-device
    api-todo:
      path: /api/todo/**
      serviceId: api-todo
    api-reminder:
      path: /api/reminder/**
      serviceId: api-reminder
    api-quote:
      path: /api/quote/**
      serviceId: api-quote
    api-weather:
      path: /api/weather/**
      serviceId: api-weather
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000