version: '3'

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#      - MONGODB_USER="user"
#      - MONGODB_PASS="pass"
#    volumes:
#      - ./data/mongodb:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

