version: '3'

services:

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - HOST_IP=192.168.1.100
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf